const totalCount = 6;
const changeit = () => {
  let num = Math.ceil(Math.random() * totalCount);
  document.body.background = "image/" + num + ".jpg";
  document.body.style.backgroundRepeat = "repeat"; // Background repeat
};

const drivers = [
  {
    position: 1,
    driver: {
      id: 25,
      name: "Max Verstappen",
      abbr: "VER",
      number: 1,
      image: "https://media.api-sports.io/formula-1/drivers/25.png",
    },
    team: {
      id: 1,
      name: "Red Bull Racing",
      logo: "https://media.api-sports.io/formula-1/teams/1.png",
    },
    points: "395.5",
    wins: null,
    behind: null,
    season: 2021,
  },
  {
    position: 2,
    driver: {
      id: 20,
      name: "Lewis Hamilton",
      abbr: "HAM",
      number: 44,
      image: "https://media.api-sports.io/formula-1/drivers/20.png",
    },
    team: {
      id: 5,
      name: "Mercedes-AMG Petronas",
      logo: "https://media.api-sports.io/formula-1/teams/5.png",
    },
    points: "387.5",
    wins: null,
    behind: null,
    season: 2021,
  },
  {
    position: 3,
    driver: {
      id: 5,
      name: "Valtteri Bottas",
      abbr: "BOT",
      number: 77,
      image: "https://media.api-sports.io/formula-1/drivers/5.png",
    },
    team: {
      id: 5,
      name: "Mercedes-AMG Petronas",
      logo: "https://media.api-sports.io/formula-1/teams/5.png",
    },
    points: 226,
    wins: null,
    behind: null,
    season: 2021,
  },
  {
    position: 4,
    driver: {
      id: 10,
      name: "Sergio Perez",
      abbr: "PER",
      number: 11,
      image: "https://media.api-sports.io/formula-1/drivers/10.png",
    },
    team: {
      id: 1,
      name: "Red Bull Racing",
      logo: "https://media.api-sports.io/formula-1/teams/1.png",
    },
    points: 190,
    wins: null,
    behind: null,
    season: 2021,
  },
  {
    position: 5,
    driver: {
      id: 24,
      name: "Carlos Sainz Jr",
      abbr: "SAI",
      number: 55,
      image: "https://media.api-sports.io/formula-1/drivers/24.png",
    },
    team: {
      id: 3,
      name: "Scuderia Ferrari",
      logo: "https://media.api-sports.io/formula-1/teams/3.png",
    },
    points: "164.5",
    wins: null,
    behind: null,
    season: 2021,
  },
  {
    position: 6,
    driver: {
      id: 49,
      name: "Lando Norris",
      abbr: "NOR",
      number: 4,
      image: "https://media.api-sports.io/formula-1/drivers/49.png",
    },
    team: {
      id: 2,
      name: "McLaren Racing",
      logo: "https://media.api-sports.io/formula-1/teams/2.png",
    },
    points: 160,
    wins: null,
    behind: null,
    season: 2021,
  },
  {
    position: 7,
    driver: {
      id: 34,
      name: "Charles Leclerc",
      abbr: "LEC",
      number: 16,
      image: "https://media.api-sports.io/formula-1/drivers/34.png",
    },
    team: {
      id: 3,
      name: "Scuderia Ferrari",
      logo: "https://media.api-sports.io/formula-1/teams/3.png",
    },
    points: 159,
    wins: null,
    behind: null,
    season: 2021,
  },
  {
    position: 8,
    driver: {
      id: 14,
      name: "Daniel Ricciardo",
      abbr: "RIC",
      number: 3,
      image: "https://media.api-sports.io/formula-1/drivers/14.png",
    },
    team: {
      id: 2,
      name: "McLaren Racing",
      logo: "https://media.api-sports.io/formula-1/teams/2.png",
    },
    points: 115,
    wins: null,
    behind: null,
    season: 2021,
  },
  {
    position: 9,
    driver: {
      id: 36,
      name: "Pierre Gasly",
      abbr: "GAS",
      number: 10,
      image: "https://media.api-sports.io/formula-1/drivers/36.png",
    },
    team: {
      id: 7,
      name: "Scuderia AlphaTauri Honda",
      logo: "https://media.api-sports.io/formula-1/teams/7.png",
    },
    points: 110,
    wins: null,
    behind: null,
    season: 2021,
  },
  {
    position: 10,
    driver: {
      id: 4,
      name: "Fernando Alonso",
      abbr: "ALO",
      number: 14,
      image: "https://media.api-sports.io/formula-1/drivers/4.png",
    },
    team: {
      id: 13,
      name: "Alpine F1 Team",
      logo: "https://media.api-sports.io/formula-1/teams/13.png",
    },
    points: 81,
    wins: null,
    behind: null,
    season: 2021,
  },
  {
    position: 11,
    driver: {
      id: 28,
      name: "Esteban Ocon",
      abbr: "OCO",
      number: 31,
      image: "https://media.api-sports.io/formula-1/drivers/28.png",
    },
    team: {
      id: 13,
      name: "Alpine F1 Team",
      logo: "https://media.api-sports.io/formula-1/teams/13.png",
    },
    points: 74,
    wins: null,
    behind: null,
    season: 2021,
  },
  {
    position: 12,
    driver: {
      id: 19,
      name: "Sebastian Vettel",
      abbr: "VET",
      number: 5,
      image: "https://media.api-sports.io/formula-1/drivers/19.png",
    },
    team: {
      id: 17,
      name: "Aston Martin F1 Team",
      logo: "https://media.api-sports.io/formula-1/teams/17.png",
    },
    points: 43,
    wins: null,
    behind: null,
    season: 2021,
  },
  {
    position: 13,
    driver: {
      id: 31,
      name: "Lance Stroll",
      abbr: "STR",
      number: 18,
      image: "https://media.api-sports.io/formula-1/drivers/31.png",
    },
    team: {
      id: 17,
      name: "Aston Martin F1 Team",
      logo: "https://media.api-sports.io/formula-1/teams/17.png",
    },
    points: 34,
    wins: null,
    behind: null,
    season: 2021,
  },
  {
    position: 14,
    driver: {
      id: 82,
      name: "Yuki Tsunoda",
      abbr: "TSU",
      number: 22,
      image: "https://media.api-sports.io/formula-1/drivers/82.png",
    },
    team: {
      id: 7,
      name: "Scuderia AlphaTauri Honda",
      logo: "https://media.api-sports.io/formula-1/teams/7.png",
    },
    points: 32,
    wins: null,
    behind: null,
    season: 2021,
  },
  {
    position: 15,
    driver: {
      id: 51,
      name: "George Russell",
      abbr: "RUS",
      number: 63,
      image: "https://media.api-sports.io/formula-1/drivers/51.png",
    },
    team: {
      id: 12,
      name: "Williams F1 Team",
      logo: "https://media.api-sports.io/formula-1/teams/12.png",
    },
    points: 16,
    wins: null,
    behind: null,
    season: 2021,
  },
  {
    position: 16,
    driver: {
      id: 7,
      name: "Kimi Raikkonen",
      abbr: "RAI",
      number: 7,
      image: "https://media.api-sports.io/formula-1/drivers/7.png",
    },
    team: {
      id: 18,
      name: "Alfa Romeo",
      logo: "https://media.api-sports.io/formula-1/teams/18.png",
    },
    points: 10,
    wins: null,
    behind: null,
    season: 2021,
  },
  {
    position: 17,
    driver: {
      id: 61,
      name: "Nicholas Latifi",
      abbr: "LAT",
      number: 6,
      image: "https://media.api-sports.io/formula-1/drivers/61.png",
    },
    team: {
      id: 12,
      name: "Williams F1 Team",
      logo: "https://media.api-sports.io/formula-1/teams/12.png",
    },
    points: 7,
    wins: null,
    behind: null,
    season: 2021,
  },
  {
    position: 18,
    driver: {
      id: 29,
      name: "Antonio Giovinazzi",
      abbr: "GIO",
      number: 99,
      image: "https://media.api-sports.io/formula-1/drivers/29.png",
    },
    team: {
      id: 18,
      name: "Alfa Romeo",
      logo: "https://media.api-sports.io/formula-1/teams/18.png",
    },
    points: 3,
    wins: null,
    behind: null,
    season: 2021,
  },
  {
    position: 19,
    driver: {
      id: 80,
      name: "Mick Schumacher",
      abbr: "MSC",
      number: 47,
      image: "https://media.api-sports.io/formula-1/drivers/80.png",
    },
    team: {
      id: 14,
      name: "Haas F1 Team",
      logo: "https://media.api-sports.io/formula-1/teams/14.png",
    },
    points: null,
    wins: null,
    behind: null,
    season: 2021,
  },
  {
    position: 20,
    driver: {
      id: 81,
      name: "Nikita Mazepin",
      abbr: "MAZ",
      number: 9,
      image: "https://media.api-sports.io/formula-1/drivers/81.png",
    },
    team: {
      id: 14,
      name: "Haas F1 Team",
      logo: "https://media.api-sports.io/formula-1/teams/14.png",
    },
    points: null,
    wins: null,
    behind: null,
    season: 2021,
  },
];

export default drivers;
