export default [
  {
    grandPrix: "Bahrain",
    date: "28 Mar 2021",
    driver: "Lewis Hamilton",
    team: "Mercedes",
    laps: "56",
    raceTime: "1:32:03.897",
  },
  {
    grandPrix: "Emilia Romagna",
    date: "18 Apr 2021",
    driver: "Max Verstappen",
    team: "Red Bull Racing Honda",
    laps: "63",
    raceTime: "2:02:34.598",
  },
  {
    grandPrix: "Portugal",
    date: "02 May 2021",
    driver: "Lewis Hamilton",
    team: "Mercedes",
    laps: "66",
    raceTime: "1:34:31.421",
  },
  {
    grandPrix: "Spain",
    date: "09 May 2021",
    driver: "Lewis Hamilton",
    team: "Mercedes",
    laps: "66",
    raceTime: "1:33:07.680",
  },
  {
    grandPrix: "Monaco",
    date: "23 May 2021",
    driver: "Max Verstappen",
    team: "Red Bull Racing Honda",
    laps: "78",
    raceTime: "1:38:56.820",
  },
  {
    grandPrix: "Azerbaijan",
    date: "06 Jun 2021",
    driver: "Sergio Perez",
    team: "Red Bull Racing Honda",
    laps: "51",
    raceTime: "2:13:36.410",
  },
  {
    grandPrix: "France",
    date: "20 Jun 2021",
    driver: "Max Verstappen",
    team: "Red Bull Racing Honda",
    laps: "53",
    raceTime: "1:27:25.770",
  },
  {
    grandPrix: "Styria",
    date: "27 Jun 2021",
    driver: "Max Verstappen",
    team: "Red Bull Racing Honda",
    laps: "71",
    raceTime: "1:22:18.925",
  },
  {
    grandPrix: "Austria",
    date: "04 Jul 2021",
    driver: "Max Verstappen",
    team: "Red Bull Racing Honda",
    laps: "71",
    raceTime: "1:23:54.543",
  },
  {
    grandPrix: "Great Britain",
    date: "18 Jul 2021",
    driver: "Lewis Hamilton",
    team: "Mercedes",
    laps: "52",
    raceTime: "1:58:23.284",
  },
  {
    grandPrix: "Hungary",
    date: "01 Aug 2021",
    driver: "Esteban Ocon",
    team: "Alpine Renault",
    laps: "70",
    raceTime: "2:04:43.199",
  },
  {
    grandPrix: "Belgium",
    date: "29 Aug 2021",
    driver: "Max Verstappen",
    team: "Red Bull Racing Honda",
    laps: "1",
    raceTime: "0:03:27.071",
  },
  {
    grandPrix: "Netherlands",
    date: "05 Sep 2021",
    driver: "Max Verstappen",
    team: "Red Bull Racing Honda",
    laps: "72",
    raceTime: "1:30:05.395",
  },
  {
    grandPrix: "Italy",
    date: "12 Sep 2021",
    driver: "Daniel Ricciardo",
    team: "McLaren Mercedes",
    laps: "53",
    raceTime: "1:21:54.365",
  },
  {
    grandPrix: "Russia",
    date: "26 Sep 2021",
    driver: "Lewis Hamilton",
    team: "Mercedes",
    laps: "53",
    raceTime: "1:30:41.001",
  },
  {
    grandPrix: "Turkey",
    date: "10 Oct 2021",
    driver: "Valtteri Bottas",
    team: "Mercedes",
    laps: "58",
    raceTime: "1:31:04.103",
  },
  {
    grandPrix: "United States",
    date: "24 Oct 2021",
    driver: "Max Verstappen",
    team: "Red Bull Racing Honda",
    laps: "56",
    raceTime: "1:34:36.552",
  },
  {
    grandPrix: "Mexico",
    date: "07 Nov 2021",
    driver: "Max Verstappen",
    team: "Red Bull Racing Honda",
    laps: "71",
    raceTime: "1:38:39.086",
  },
  {
    grandPrix: "Brazil",
    date: "14 Nov 2021",
    driver: "Lewis Hamilton",
    team: "Mercedes",
    laps: "71",
    raceTime: "1:32:22.851",
  },
  {
    grandPrix: "Qatar",
    date: "21 Nov 2021",
    driver: "Lewis Hamilton",
    team: "Mercedes",
    laps: "57",
    raceTime: "1:24:28.471",
  },
  {
    grandPrix: "Saudi Arabia",
    date: "05 Dec 2021",
    driver: "Lewis Hamilton",
    team: "Mercedes",
    laps: "50",
    raceTime: "2:06:15.118",
  },
  {
    grandPrix: "Abu Dhabi",
    date: "12 Dec 2021",
    driver: "Max Verstappen",
    team: "Red Bull Racing Honda",
    laps: "58",
    raceTime: "1:30:17.345",
  },
];
